language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install:
- pip install numpy scipy
- python setup.py install
script:
- python pypower/t/test_pypower.py
deploy:
  provider: pypi
  user: "__token__"
  password: "$PYPI_TOKEN"
  on:
    tags: true
    repo: rwl/PYPOWER
    branch: master
    python: '3.6'
