language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install:
- pip install numpy scipy tox-travis
- python setup.py install
script: tox
deploy:
  provider: pypi
  user: rwl
  password:
    secure: "YZjUo3RHhyq9rsg+8NGP2Bn1+J5kQxXfuO7G2ACwvAeabdHqhzTE0eDOObaeS+vnoUHxrRuJWFB1HvDH7BlegBuTS0l+s8lssfFNrasnMlZ3xpiGNGbcgrftxYnaPE9BSN8Ge7w8oa1QnkfqcPuYN2BoSYXv1LitCNi/bqf0JcA="
  on:
    tags: true
    repo: rwl/PYPOWER
    branch: master
    python: '3.9'
